/*=============================================================================
 * File       :  ENERGY.C
 *
 * Project    :  SK0153 - LINKY DIN 4G
 * Description:  PROGRAM - energy meter
 *
 * Copyright Shitek Technology SRL (c) 2010
 *=============================================================================*/




/*===========================================================================
 * INCLUDES
 *===========================================================================*/
/* standard includes */
#include <math.h>

/* API      includes */
#include "ql_api_osi.h"

/* user     includes */
#include "alarm.h"
#include "boot.h"
#include "debug_my.h"
#include "drvtemperature.h"
#include "energy.h"
#include "fw_config.h"
#include "outputs.h"
#include "program_flash.h"
#include "typedef.h"




/*===========================================================================
 * DEFINES
 *===========================================================================*/
/* maximum ADC value status */
#define ADC_VALUE__OK                          0    // status - ADC value regular
#define ADC_VALUE__MAX                         1    // status - ADC value too high (above the maximum temperature)

/* duration before changing temperature status (sec) */
#if (FW_CONFIG__TEST__MODE_1 == FW_CONFIG__TEST__MODE_1__NORMAL)
#define TIME_SEC_TEMP_STATUS_CHANGE            (60 + 1)
#endif
#if (FW_CONFIG__TEST__MODE_1 == FW_CONFIG__TEST__MODE_1__FAST)
#define TIME_SEC_TEMP_STATUS_CHANGE            (10 + 1)
#endif

/*-----------------------------------------------------------------------------
 * task message IDs
 *-----------------------------------------------------------------------------*/
/* task message IDs */
#define TASK_MSG_ID__NEW_ADC_VALUE             (11000 | (QL_COMPONENT_APP_START << 16))
#define TASK_MSG_ID__TIMEOUT_ADC_VALUE_START   (11001 | (QL_COMPONENT_APP_START << 16))
#define TASK_MSG_ID__TIMEOUT_ADC_VALUE_STOP    (11002 | (QL_COMPONENT_APP_START << 16))

/* debug string length */
#define MAX_LENGTH_DEBUG_STRING                200




/*===========================================================================
 * VARIABLES
 *===========================================================================*/
/* debug string */
static       ascii                     Energy_DebugString[MAX_LENGTH_DEBUG_STRING + 1];

/*-----------------------------------------------------------------------------
 * Status
 *-----------------------------------------------------------------------------*/
/* status - internal temperature status */
static       ENERGY__STATUS__ADC_VALUE Energy_Status_AdcValue;
static const ENERGY__STATUS__ADC_VALUE Energy_Status_AdcValueDefault =
{
    0,                /* power generated by the plant      */
    0,                /* power drawn     by the user       */
    0,                /* power fed into the grid           */
    ADC_VALUE__OK,    /* internal temperature status       */
    FALSE,            /* indication of status change timer */
};


/*-----------------------------------------------------------------------------
 * Configurations
 *-----------------------------------------------------------------------------*/
/* configuration - internal maximum temperature */
static       ENERGY__CONFIG__ADC_VALUE Energy_Config_AdcValue;
static const ENERGY__CONFIG__ADC_VALUE Energy_Config_AdcValueDefault =
{
    FALSE,
    1000,             /* maximum ADC value for alarm (mV)  */
};


/*---------------------------------------------------------------------------
 * OpenAT handlers
 *---------------------------------------------------------------------------*/
/* timer handler */
static       ql_timer_t                Energy_TimerHandler_TimerAdcValueStart;  /* timer for ADC value start */
static       ql_timer_t                Energy_TimerHandler_TimerAdcValueStop;   /* timer for ADC value stop  */




/*=============================================================================
 * FUNCTION PROTOTYPES
 *=============================================================================*/
/* task */
       void Energy_TaskEnergy(void *argument);

/* task events */
static void Energy_NewAdcValues(u16 adc_value_int, u16 adc_value_ext);

/*-----------------------------------------------------------------------------
 * get/set
 *-----------------------------------------------------------------------------*/
/* get/set "ADC value" status */
       void Energy_Status_AdcValue_GetDefault(ENERGY__STATUS__ADC_VALUE *ptr_data);
       void Energy_Status_AdcValue_Get       (ENERGY__STATUS__ADC_VALUE *ptr_data);
       void Energy_Status_AdcValue_Set       (ENERGY__STATUS__ADC_VALUE *ptr_data);
       bool Energy_Status_AdcValue_IsValid   (ENERGY__STATUS__ADC_VALUE *ptr_data);

/* get/set "ADC value" configuration */
       void Energy_Config_AdcValue_GetDefault(ENERGY__CONFIG__ADC_VALUE *ptr_data);
       void Energy_Config_AdcValue_Get       (ENERGY__CONFIG__ADC_VALUE *ptr_data);
       void Energy_Config_AdcValue_Set       (ENERGY__CONFIG__ADC_VALUE *ptr_data);
       bool Energy_Config_AdcValue_IsValid   (ENERGY__CONFIG__ADC_VALUE *ptr_data);


/*-----------------------------------------------------------------------------
 * action on timers
 *-----------------------------------------------------------------------------*/
static void Energy_TimerAdcValueStart_Start(u32 time_value, bool periodic);
static void Energy_TimerAdcValueStart_Stop (void);

static void Energy_TimerAdcValueStop_Start (u32 time_value, bool periodic);
static void Energy_TimerAdcValueStop_Stop  (void);


/*-----------------------------------------------------------------------------
 * Open AT callback functions
 *-----------------------------------------------------------------------------*/
/* message callback functions */
static void Energy_AdlCallback_Message_TaskMsg(ql_event_t *msg_identifier);

/* timer   callback functions */
static void Energy_AdlCallback_Timer_TimerAdcValueStart(void *context);
static void Energy_AdlCallback_Timer_TimerAdcValueStop (void *context);



/*=============================================================================
 * Function   : Energy_TaskEnergy
 *
 * Description: energy meter task
 * Input      : -
 * Output     : -
 *=============================================================================*/
void Energy_TaskEnergy(void *argument)
{
    ql_event_t event;
    QlOSStatus err;


    Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "TASK ENTRY POINT - ALARM_TMAX - START", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);


    /* registered the function for signal of new available temperatures */
    DrvTemperature_RegisterSignalNewAdcValues(Energy_NewAdcValues);


    /* creation of timer "TimerAdcValueStart" */
    err = ql_rtos_timer_create(&Energy_TimerHandler_TimerAdcValueStart, QL_TIMER_IN_SERVICE, Energy_AdlCallback_Timer_TimerAdcValueStart, NULL);
    if (err != QL_OSI_SUCCESS)
    {
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "QL FUNCTION - ql_rtos_timer_create - ERROR", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }

    /* creation of timer "TimerAdcValueStop" */
    err = ql_rtos_timer_create(&Energy_TimerHandler_TimerAdcValueStop, QL_TIMER_IN_SERVICE, Energy_AdlCallback_Timer_TimerAdcValueStop, NULL);
    if (err != QL_OSI_SUCCESS)
    {
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "QL FUNCTION - ql_rtos_timer_create - ERROR", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }


    for (;;)
    {
        err = ql_event_try_wait(&event);
        if (err == QL_OSI_SUCCESS)
        {
            /* process the received event */
            Energy_AdlCallback_Message_TaskMsg(&event);
        }
    }
}




/*===========================================================================
 * Function   : Energy_NewAdcValues
 *
 * Description: signal new ADC values available (internal and external)
 * Input      : - adc_value_int: new internal ADC value (mV)
 *              - adc_value_ext: new external ADC value (mV)
 * Output     : -
 *===========================================================================*/
static void Energy_NewAdcValues(u16 adc_value_int, u16 adc_value_ext)
{
    ql_event_t event;
    QlOSStatus err;


    if (Energy_Config_AdcValue.alarm_enabled_status)
    {
        event.id     = TASK_MSG_ID__NEW_ADC_VALUE;
        event.param1 = adc_value_int;
        event.param2 = adc_value_ext;

        err = ql_rtos_event_send(Boot_TaskRef_Energy, &event);
        if (err != QL_OSI_SUCCESS)
        {
            Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "ql_rtos_event_send ERROR", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
        }
        else
        {
            Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "ql_rtos_event_send OK"   , __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
        }
    }
}




/*=============================================================================
 * Function   : Energy_AlarmAdcValue
 *
 * Description: verify if there is an "ADC value alarm" condition
 * Input      : - adc_value: actual ADC value (mV)
 * Output     : -
 *=============================================================================*/
static void Energy_AlarmAdcValue(s16 adc_value)
{
    switch (Energy_Status_AdcValue.status_adc_value)
    {
        // status - temperature regular
        case ADC_VALUE__OK:
            /* status - temperature regular */
            if (adc_value >= Energy_Config_AdcValue.adc_value)   // without hysteresis
            {
                /* "new internal temperature" higher (or equal) than "maximum internal temperature for alarm" */
                if (!Energy_Status_AdcValue.status_change_timer)
                {
                    /* status change timer not active */

                    Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "ADC value: start MAX", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);

                    Energy_Status_AdcValue.status_change_timer = TRUE;

                    /* request the backup to flash objects */
                    ProgramFlash_RequestWriteBackup(PROGRAM_FLASH__HANDLE_INDEX__018_ENERGY_INFO, PROGRAM_FLASH__FLASH_ID__018_ENERGY_INFO__ADC_VALUE_STATUS);

                    Energy_TimerAdcValueStart_Start(TIME_SEC_TEMP_STATUS_CHANGE * 1000L, FALSE);
                }
            }
            else
            {
                /* "new internal temperature" lower             than "maximum internal temperature for alarm" */
                if ( Energy_Status_AdcValue.status_change_timer)
                {
                    /* status change timer     active */

                    Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "ADC value: stop MAX" , __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);

                    Energy_Status_AdcValue.status_change_timer = FALSE;

                    /* request the backup to flash objects */
                    ProgramFlash_RequestWriteBackup(PROGRAM_FLASH__HANDLE_INDEX__018_ENERGY_INFO, PROGRAM_FLASH__FLASH_ID__018_ENERGY_INFO__ADC_VALUE_STATUS);

                    Energy_TimerAdcValueStart_Stop();
                }
            }
            break;


        // status - ADC value too high (above the maximum)
        case ADC_VALUE__MAX:
            /* status - ADC value too high (above the maximum) */

            if (adc_value <= 0                               )   // with    hysteresis
            {
                if (!Energy_Status_AdcValue.status_change_timer)
                {
                    /* status change timer not active */

                    Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "ADC value: start OK" , __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);

                    Energy_Status_AdcValue.status_change_timer = TRUE;

                    /* request the backup to flash objects */
                    ProgramFlash_RequestWriteBackup(PROGRAM_FLASH__HANDLE_INDEX__018_ENERGY_INFO, PROGRAM_FLASH__FLASH_ID__018_ENERGY_INFO__ADC_VALUE_STATUS);

                    Energy_TimerAdcValueStop_Start(TIME_SEC_TEMP_STATUS_CHANGE * 1000L, FALSE);
                }
            }
            else
            {
                if ( Energy_Status_AdcValue.status_change_timer)
                {
                    /* status change timer     active */

                    Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "ADC value: stop OK"  , __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);

                    Energy_Status_AdcValue.status_change_timer = FALSE;

                    /* request the backup to flash objects */
                    ProgramFlash_RequestWriteBackup(PROGRAM_FLASH__HANDLE_INDEX__018_ENERGY_INFO, PROGRAM_FLASH__FLASH_ID__018_ENERGY_INFO__ADC_VALUE_STATUS);

                    Energy_TimerAdcValueStop_Stop();
                }
            }
            break;


        // status - ADC value status unknown
        default:
            //@@@ TO DO
            break;
    }
}




/*===========================================================================
 * Function   : Energy_Config_AdcValue_GetDefault
 *
 * Description: get the default "ADC value" status
 * Input      : - ptr_data: pointer to store the values got
 * Output     : -
 *===========================================================================*/
void Energy_Status_AdcValue_GetDefault(ENERGY__STATUS__ADC_VALUE *ptr_data)
{
    *ptr_data = Energy_Status_AdcValueDefault;
}




/*===========================================================================
 * Function   : Energy_Status_AdcValue_Get
 *
 * Description: get the "ADC value" status
 * Input      : - ptr_data: pointer to store the values got
 * Output     : -
 *===========================================================================*/
void Energy_Status_AdcValue_Get(ENERGY__STATUS__ADC_VALUE *ptr_data)
{
    *ptr_data = Energy_Status_AdcValue;
}




/*===========================================================================
 * Function   : Energy_Status_AdcValue_Set
 *
 * Description: set the "ADC value" status
 * Input      : - ptr_data: pointer to the values to set
 * Output     : -
 *===========================================================================*/
void Energy_Status_AdcValue_Set(ENERGY__STATUS__ADC_VALUE *ptr_data)
{
    Energy_Status_AdcValue = *ptr_data;
}




/*===========================================================================
 * Function   : Energy_Status_AdcValue_IsValid
 *
 * Description: check if the "ADC value" status is valid
 * Input      : - ptr_data: pointer to the values to be checked
 * Output     : - FALSE: configuration is not valid
 *              - TRUE : configuration is     valid
 *===========================================================================*/
bool Energy_Status_AdcValue_IsValid(ENERGY__STATUS__ADC_VALUE *ptr_data)
{
    return TRUE;
}




/*===========================================================================
 * Function   : Energy_Config_AdcValue_GetDefault
 *
 * Description: get the default "ADC value" configuration
 * Input      : - ptr_data: pointer to store the values got
 * Output     : -
 *===========================================================================*/
void Energy_Config_AdcValue_GetDefault(ENERGY__CONFIG__ADC_VALUE *ptr_data)
{
    *ptr_data = Energy_Config_AdcValueDefault;
}




/*===========================================================================
 * Function   : Energy_Config_AdcValue_Get
 *
 * Description: get the "ADC value" configuration
 * Input      : - ptr_data: pointer to store the values got
 * Output     : -
 *===========================================================================*/
void Energy_Config_AdcValue_Get(ENERGY__CONFIG__ADC_VALUE *ptr_data)
{
    *ptr_data = Energy_Config_AdcValue;
}




/*===========================================================================
 * Function   : Energy_Config_AdcValue_Set
 *
 * Description: set the "ADC value" configuration
 * Input      : - ptr_data: pointer to the values to set
 * Output     : -
 *===========================================================================*/
void Energy_Config_AdcValue_Set(ENERGY__CONFIG__ADC_VALUE *ptr_data)
{
    Energy_Config_AdcValue = *ptr_data;
}




/*===========================================================================
 * Function   : Energy_Config_AdcValue_IsValid
 *
 * Description: check if the "ADC value" configuration is valid
 * Input      : - ptr_data: pointer to the values to be checked
 * Output     : - FALSE: configuration is not valid
 *              - TRUE : configuration is     valid
 *===========================================================================*/
bool Energy_Config_AdcValue_IsValid(ENERGY__CONFIG__ADC_VALUE *ptr_data)
{
    if (
         (ptr_data->adc_value < 1    ) ||
         (ptr_data->adc_value > 11500)
       )
    {
        return FALSE;
    }

    return TRUE;
}




/*=============================================================================
 * Function   : Energy_TimerAdcValueStart_Start
 *
 * Description: start the "internal maximum temperature start" timer
 * Input      : - time_value: timeout value (ms)
 *              - periodic  : timer type indication
 *                            - FALSE: one shot timer
 *                            - TRUE : periodic timer
 * Output     : -
 *=============================================================================*/
static void Energy_TimerAdcValueStart_Start(u32 time_value, bool periodic)
{
    QlOSStatus err;


    Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "Start \"ADC value start\" timer", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);

    /* start the timer */
    err = ql_rtos_timer_start(Energy_TimerHandler_TimerAdcValueStart, time_value, periodic);
    if (err != QL_OSI_SUCCESS)
    {
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "QL FUNCTION - ql_rtos_timer_start - ERROR", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }
    else
    {
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "QL FUNCTION - ql_rtos_timer_start - OK"   , __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }
}




/*=============================================================================
 * Function   : Energy_TimerAdcValueStart_Stop
 *
 * Description: stop the "internal maximum temperature start" timer
 * Input      : -
 * Output     : -
 *=============================================================================*/
static void Energy_TimerAdcValueStart_Stop(void)
{
    QlOSStatus err;


    Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "Stop \"ADC value start\" timer", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);

    /* stop the timer (if enabled) */
    err = ql_rtos_timer_stop(Energy_TimerHandler_TimerAdcValueStart);
    if (err != QL_OSI_SUCCESS)
    {
        snprintf(Energy_DebugString, sizeof(Energy_DebugString), "QL FUNCTION - ql_rtos_timer_stop ERROR %d", err);
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, Energy_DebugString, __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }
    else
    {
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "QL FUNCTION - ql_rtos_timer_stop - OK"   , __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }
}




/*=============================================================================
 * Function   : Energy_TimerAdcValueStop_Start
 *
 * Description: start the "internal maximum temperature stop" timer
 * Input      : - time_value: timeout value (ms)
 *              - periodic  : timer type indication
 *                            - FALSE: one shot timer
 *                            - TRUE : periodic timer
 * Output     : -
 *=============================================================================*/
static void Energy_TimerAdcValueStop_Start(u32 time_value, bool periodic)
{
    QlOSStatus err;


    Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "Start \"ADC value stop\" timer", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);

    /* start the timer */
    err = ql_rtos_timer_start(Energy_TimerHandler_TimerAdcValueStop, time_value, periodic);
    if (err != QL_OSI_SUCCESS)
    {
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "QL FUNCTION - ql_rtos_timer_start - ERROR", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }
    else
    {
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "QL FUNCTION - ql_rtos_timer_start - OK"   , __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }
}




/*=============================================================================
 * Function   : Energy_TimerAdcValueStop_Stop
 *
 * Description: stop the "internal maximum temperature stop" timer
 * Input      : -
 * Output     : -
 *=============================================================================*/
static void Energy_TimerAdcValueStop_Stop(void)
{
    QlOSStatus err;


    Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "Stop \"ADC value stop\" timer", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);

    /* stop the timer (if enabled) */
    err = ql_rtos_timer_stop(Energy_TimerHandler_TimerAdcValueStop);
    if (err != QL_OSI_SUCCESS)
    {
        snprintf(Energy_DebugString, sizeof(Energy_DebugString), "QL FUNCTION - ql_rtos_timer_stop ERROR %d", err);
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, Energy_DebugString, __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }
    else
    {
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "QL FUNCTION - ql_rtos_timer_stop - OK"   , __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }
}




/*===========================================================================
 * Function   : Energy_AdlCallback_Message_TaskMsg
 *
 * Description: - task message callback
 * Input      : - ptr_data:
 * Output     : -
 *===========================================================================*/
static void Energy_AdlCallback_Message_TaskMsg(ql_event_t *msg_identifier)
{
    s16   adc_value_int;
    s16   adc_value_ext;

    float power_generated;
    float power_drawn;
    float power_fed;

    s16   power_generated_int;
    s16   power_drawn_int;
    s16   power_fed_int;

    bool  result;


    /* avoid compiler warning unused-but-set-variable */
    (void)result;


    /* debug */
    snprintf(Energy_DebugString, sizeof(Energy_DebugString), "CALLBACK     - MESSAGE     - TASK ENERGY - msg identifier: %d", msg_identifier->id);
    Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, Energy_DebugString, __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);


    switch (msg_identifier->id)
    {
        // event - new internal temperature available
        case TASK_MSG_ID__NEW_ADC_VALUE:
            /* extract the parameters */
            adc_value_int = (s16)msg_identifier->param1;
            adc_value_ext = (s16)msg_identifier->param2;

            snprintf(Energy_DebugString, sizeof(Energy_DebugString), "Current ADC values: %d,%d (mV)", adc_value_int, adc_value_ext);
            Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, Energy_DebugString, __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);


            snprintf(Energy_DebugString,
                     sizeof(Energy_DebugString),
                     "ADC status before new value: %d,%d",
                     Energy_Status_AdcValue.status_adc_value,
                     Energy_Status_AdcValue.status_change_timer);
            Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, Energy_DebugString, __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);


            power_generated = (float)adc_value_int * 2.3f;
            power_drawn     = (float)adc_value_ext * 2.3f;
            power_fed       = power_generated - power_drawn;

            power_generated_int = (s16)lroundf(power_generated);
            power_drawn_int     = (s16)lroundf(power_drawn);
            power_fed_int       = (s16)lroundf(power_fed);

            Energy_Status_AdcValue.power_generated = power_generated_int;
            Energy_Status_AdcValue.power_drawn     = power_drawn_int;
            Energy_Status_AdcValue.power_fed       = power_fed_int;

            /* check the ADC value */
            Energy_AlarmAdcValue(power_fed_int);
            break;



        // event - timeout internal maximum temperature start
        case TASK_MSG_ID__TIMEOUT_ADC_VALUE_START:
            Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "ADC value: MAX", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);

            /* update the ADC value status */
            Energy_Status_AdcValue.status_adc_value    = ADC_VALUE__MAX;
            Energy_Status_AdcValue.status_change_timer = FALSE;

            /* request the backup to flash objects */
            ProgramFlash_RequestWriteBackup(PROGRAM_FLASH__HANDLE_INDEX__018_ENERGY_INFO, PROGRAM_FLASH__FLASH_ID__018_ENERGY_INFO__ADC_VALUE_STATUS);

            if (Energy_Config_AdcValue.alarm_enabled_status)
            {
                /* enable output 1 */
                Outputs_Event_ManualInt_On();
            }
            break;


        // event - timeout internal maximum temperature stop
        case TASK_MSG_ID__TIMEOUT_ADC_VALUE_STOP:
            Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "ADC value: OK" , __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);

            /* update the ADC value status */
            Energy_Status_AdcValue.status_adc_value    = ADC_VALUE__OK;
            Energy_Status_AdcValue.status_change_timer = FALSE;

            /* request the backup to flash objects */
            ProgramFlash_RequestWriteBackup(PROGRAM_FLASH__HANDLE_INDEX__018_ENERGY_INFO, PROGRAM_FLASH__FLASH_ID__018_ENERGY_INFO__ADC_VALUE_STATUS);

            if (Energy_Config_AdcValue.alarm_enabled_status)
            {
                /* disable output 1 */
                Outputs_Event_ManualInt_Off();
            }
            break;



        // unknown event
        default:
            break;
    }
}




/*=============================================================================
 * Function   : Energy_AdlCallback_Timer_TimerAdcValueStart
 *
 * Description:
 * Input      : - context:
 * Output     : -
 *=============================================================================*/
static void Energy_AdlCallback_Timer_TimerAdcValueStart(void *context)
{
    ql_event_t event;
    QlOSStatus err;


    Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "CALLBACK     - TIMER       - TEMPERATURE MAX INT START", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);


    event.id = TASK_MSG_ID__TIMEOUT_ADC_VALUE_START;

    err = ql_rtos_event_send(Boot_TaskRef_Energy, &event);
    if (err != QL_OSI_SUCCESS)
    {
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "ql_rtos_event_send ERROR", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }
    else
    {
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "ql_rtos_event_send OK"   , __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }
}




/*=============================================================================
 * Function   : Energy_AdlCallback_Timer_TimerAdcValueStop
 *
 * Description:
 * Input      : - context:
 * Output     : -
 *=============================================================================*/
static void Energy_AdlCallback_Timer_TimerAdcValueStop(void *context)
{
    ql_event_t event;
    QlOSStatus err;


    Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "CALLBACK     - TIMER       - TEMPERATURE MAX INT STOP", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);


    event.id = TASK_MSG_ID__TIMEOUT_ADC_VALUE_STOP;

    err = ql_rtos_event_send(Boot_TaskRef_Energy, &event);
    if (err != QL_OSI_SUCCESS)
    {
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "ql_rtos_event_send ERROR", __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }
    else
    {
        Debug_SendDebugString1(DEBUG_TRACE_LEVEL_ENERGY, DEBUG_TRACE_TYPE_LOW, "ql_rtos_event_send OK"   , __FILE__, __LINE__, (ascii *)__FUNCTION__, 0);
    }
}
