"""Document Coverage Matrix corpus — Chief Hardware Architect view of PF2 CCI."""

from __future__ import annotations

# Subsystem coverage rows:
# block, subsystem, required_knowledge, available_documents, missing_documents, priority, impact_if_missing, status, gate, source_ids

DOCUMENT_COVERAGE = [
    {
        "block": "LAB",
        "subsystem": "TesPro TG-524 (OpenWrt lab DUT)",
        "required_knowledge": "Port map, RS485, DI/DO limits, OpenWrt SDK, Secure Boot / TPM",
        "available": "TG-500 datasheet; spec response form; lab platform freeze doc",
        "missing": "OpenWrt SDK from TesPro; confirmed SKU TG-424 vs TG-524",
        "priority": "P0",
        "impact": "Cannot cross-compile or run on-target tests until SDK + hardware",
        "status": "PARTIAL",
        "gate": "Lab bring-up",
        "source_ids": "ccli-tg500-lab-platform; ccli-tespro-tg500-ds; ccli-tespro-tg424-response",
    },
    {
        "block": "MOCK",
        "subsystem": "Raspberry Pi (pre-hardware mock)",
        "required_knowledge": "Same test vectors as TG-524; pymodbus + libiec61850 native build",
        "available": "Validation strategy; mocking bench BOM; protocol library refs",
        "missing": "apps/ccli scaffold; Pi validation runbook",
        "priority": "P0",
        "impact": "Delayed L1/L2 protocol work before TG-524 arrives",
        "status": "PARTIAL",
        "gate": "Wave A",
        "source_ids": "ccli-validation-strategy; ccli-mocking-bench-bom; ccli-github-protocol-libs",
    },
    {
        "block": "C1",
        "subsystem": "Ethernet — Eth_A / Eth_B / Plant×2",
        "required_knowledge": "4-domain isolation; switch vs dual-PHY; GOOSE L2; magjacks; EMC Ethernet",
        "available": "CEI Allegato O/T; Network_Architecture.drawio; Interface_Matrix; Prototype BOM category; Validation strategy",
        "missing": "C1 topology ADR (locked); Switch/PHY DS (MPN); Magjack DS; Pin budget for Ethernet pins",
        "priority": "P0",
        "impact": "Wrong segmentation → grid rejection; GOOSE/MMS failure; carrier respin",
        "status": "MISSING",
        "gate": "D3/D12 + ADR-005",
        "source_ids": "cei-0-16-allegato-o; cei-0-16-allegato-t; ccli-prototype-bom",
    },
    {
        "block": "C2",
        "subsystem": "2× Isolated RS485 Modbus RTU",
        "required_knowledge": "Opto-isolated transceiver; RJ45 8/8 plant serial; EMC; termination",
        "available": "Vendor selection C2; Interface_Matrix; SK0146 RS485 sheet (on disk, NOT in RAG); ATEX reuse craft",
        "missing": "Isolated RS485 transceiver DS (MPN); Connector pinout freeze; SK0146 RAG ingest",
        "priority": "P1",
        "impact": "Schematic hold on C2; wrong EMC scope if kit DB9 used as product proof",
        "status": "MISSING",
        "gate": "D13",
        "source_ids": "ccli-vendor-selection; sk0146-blk_ref_a_rs485 (NOT_IN_RAG)",
    },
    {
        "block": "C3",
        "subsystem": "Protocols — IEC61850 / IEC104 / Modbus",
        "required_knowledge": "MMS, GOOSE, 60870-5-104, Modbus TCP/RTU; commercial 61850 license",
        "available": "CEI O/T; Validation strategy; GitHub libiec61850/lib60870 refs; Mocking bench SW list; Regs classification",
        "missing": "GOOSE lab runbook; IEC104 stack choice + test vectors; MZ commercial license quote; Analyzer Modbus map",
        "priority": "P0",
        "impact": "Cannot prove DSO/operator path; legal risk shipping GPLv3; plant poll blocked",
        "status": "PARTIAL",
        "gate": "D-LIC / D8",
        "source_ids": "cei-0-16-allegato-o; ccli-validation-strategy; ccli-project-roadmap",
    },
    {
        "block": "C4",
        "subsystem": "DI 10–120 Vdc ×5 + DO dry contact ×3",
        "required_knowledge": "Opto DI conditioner; relay class; surge; PF2 failsafe; Wave B fixture",
        "available": "Vendor selection C4; Validation + Mocking Bench BOM Wave B; SK0146 DIN/DOUT (craft only)",
        "missing": "Opto DI DS (MPN); Relay DS (MPN); Contact VA rating; HW WDT→DO failsafe note",
        "priority": "P1",
        "impact": "False curtailment / unsafe DO; cannot freeze schematic C4",
        "status": "MISSING",
        "gate": "D11",
        "source_ids": "ccli-vendor-selection; ccli-mocking-bench-bom; ccli-validation-strategy",
    },
    {
        "block": "C5",
        "subsystem": "GNSS time sync (NMEA + PPS)",
        "required_knowledge": "Module UART/I2C; PPS GPIO; antenna; industrial temp; optional PTP",
        "available": "Vendor selection C5; Prototype BOM category; Power_Tree stub; Validation L3 deferred note",
        "missing": "GNSS module DS (MPN); Antenna DS; PPS pin in pin budget; PTP requirement decision",
        "priority": "P1",
        "impact": "Event timestamp mismatch; L3 time tests blocked",
        "status": "MISSING",
        "gate": "D9",
        "source_ids": "ccli-prototype-bom; ccli-vendor-selection",
    },
    {
        "block": "C6",
        "subsystem": "Secure Boot + Secure Element",
        "required_knowledge": "HAB fuse policy; signed image CI; SE/TPM key storage; 62443 zones",
        "available": "TG-524 Secure Boot / TPM brochure; Architecture framework; Regs class; protocol libs",
        "missing": "Product key hierarchy doc; SE/TPM DS (MPN or SoM SKU proof); IEC 62443 SL/zones diagram; 62351 test plan",
        "priority": "P0",
        "impact": "Cyber assessment fail; keys in filesystem (R-SEC-001)",
        "status": "PARTIAL",
        "gate": "D15 / D-CERT",
        "source_ids": "ccli-tg500-lab-platform; ccli-github-protocol-libs; ccli-cci-module-regs-class",
    },
    {
        "block": "C7",
        "subsystem": "LTE backup (optional rev A)",
        "required_knowledge": "Cat.1 module; antenna; SIM; firewall vs Eth_A",
        "available": "Prototype BOM partial; Quectel-class refs in Telematry; Vendor selection optional",
        "missing": "CCI-locked LTE module DS; RF/antenna layout guide for carrier",
        "priority": "P3",
        "impact": "Rev A slip only — must not block Architecture Freeze",
        "status": "PARTIAL",
        "gate": "D10",
        "source_ids": "ccli-prototype-bom",
    },
    {
        "block": "C8",
        "subsystem": "Local console / commissioning USB",
        "required_knowledge": "USB out of cert path; RBAC; physical access",
        "available": "Dev Board USB; Architecture framework; Interface_Matrix",
        "missing": "Commissioning security procedure (62443)",
        "priority": "P2",
        "impact": "Attack surface if USB unconstrained",
        "status": "PARTIAL",
        "gate": "—",
        "source_ids": "ccli-toradex-verdin-devboard; ccli-architecture-framework",
    },
    {
        "block": "C9",
        "subsystem": "Mechanical / DIN-rail enclosure",
        "required_knowledge": "Thermal envelope; connector placement; IP rating if required",
        "available": "Prototype BOM category; Architecture mech note",
        "missing": "Enclosure drawing; Thermal budget; Connector family freeze",
        "priority": "P2",
        "impact": "PCB/enclosure mismatch; thermal failure in cabinet",
        "status": "MISSING",
        "gate": "D18",
        "source_ids": "ccli-prototype-bom",
    },
    {
        "block": "C10",
        "subsystem": "Power — 12–24 Vdc isolated input",
        "required_knowledge": "Isolated DC-DC; sequencing; eFuse; brownout; load budget; DI field supply independence",
        "available": "Power_Tree.drawio (conceptual); Prototype BOM C10 category; Kit 7–24 V note",
        "missing": "PSU module DS (MPN); Current/load budget; Hold-up / brownout analysis",
        "priority": "P1",
        "impact": "Field brownout; relay dropouts; SoM reset under load",
        "status": "MISSING",
        "gate": "D14",
        "source_ids": "ccli-prototype-bom",
    },
    {
        "block": "SYS",
        "subsystem": "System architecture & CEI PF2",
        "required_knowledge": "Annex O/T PF2; Eth domains; curtailment safe-state; verification L1–L4",
        "available": "Architecture Framework; DRB CCLI-DRB-001; draw.io set; Interface/BOM/Risk/Verification matrices; architecture.db; CEI O/T",
        "missing": "Pin budget; Carrier freeze doc; C1 ADR locked",
        "priority": "P0",
        "impact": "Architecture Freeze remains NO-GO",
        "status": "PARTIAL",
        "gate": "D0/D3/D4",
        "source_ids": "ccli-architecture-framework; ccli-design-review-board-pf2; cei-0-16-allegato-o",
    },
    {
        "block": "VAL",
        "subsystem": "Validation / mocking bench",
        "required_knowledge": "Wave A–D fixtures; GOOSE/MMS/104/Modbus tests; evidence paths",
        "available": "Validation strategy (INGESTED); Mocking Bench BOM (INGESTED); Verification_Matrix",
        "missing": "GOOSE test procedure; IEC104 client choice; Real analyzer register map; Evidence folder convention",
        "priority": "P1",
        "impact": "False confidence from kit-only tests; delayed L2/L3",
        "status": "PARTIAL",
        "gate": "—",
        "source_ids": "ccli-validation-strategy; ccli-mocking-bench-bom",
    },
    {
        "block": "SEC",
        "subsystem": "Cybersecurity / IEC 62443 / CRA",
        "required_knowledge": "Zones/conduits; SL-T; CRA; secure boot ceremony",
        "available": "Regs classification; EU CRA PDF on disk; RED directive PDF; GitHub security layers",
        "missing": "62443 zones diagram; SL target; Licensed 62443/62351 extracts; Key ceremony SOP",
        "priority": "P0",
        "impact": "Certification delay; weak product security story",
        "status": "PARTIAL",
        "gate": "D-CERT",
        "source_ids": "ccli-cci-module-regs-class; eu-2024-2847-cra",
    },
    {
        "block": "ARCHIVE",
        "subsystem": "Alternate SoM / custom carrier (removed)",
        "required_knowledge": "Historical comparison only — not active path",
        "available": "Historical study in _archive/som-study/",
        "missing": "—",
        "priority": "—",
        "impact": "N/A — TG-524 is final product SoC",
        "status": "ARCHIVED",
        "gate": "—",
        "source_ids": "—",
    },
]

# Explicit missing documents list for Missing Documents Report
MISSING_DOCUMENTS = [
    {"doc_id": "MD-001", "document": "TesPro OpenWrt SDK", "subsystem": "LAB", "target": "vendor package", "source_id": "ccli-soc-freeze", "priority": "P0", "impact": "Cannot cross-compile for TG-524", "action": "Request with TG-524 PO", "blocks_gate": "Lab bring-up"},
    {"doc_id": "MD-002", "document": "TG-424 vs TG-524 SKU confirmation", "subsystem": "LAB", "target": "vendor email / PO", "source_id": "ccli-tg500-lab-platform", "priority": "P0", "impact": "Wrong device ordered", "action": "Confirm with TesPro FAE", "blocks_gate": "PO"},
    {"doc_id": "MD-003", "document": "Lab port map (Eth_A/B/plant labels)", "subsystem": "LAB", "target": "08-engineering/CCI_TG500_Lab_Platform.md", "source_id": "ccli-tg500-lab-platform", "priority": "P0", "impact": "Blocks L2 HIL wiring", "action": "Label ports on receipt", "blocks_gate": "L2"},
    {"doc_id": "MD-004", "document": "CCI Carrier Block Diagram (frozen)", "subsystem": "Carrier", "target": "08-engineering/CCI_Carrier_Block_Diagram.md", "source_id": "ccli-carrier-block", "priority": "P0", "impact": "No Altium-ready freeze; C1/C2/C4/C5 open", "action": "Export/freeze from Hardware_Architecture.drawio", "blocks_gate": "D4"},
    {"doc_id": "MD-005", "document": "C1 Ethernet topology ADR (locked)", "subsystem": "C1 Ethernet", "target": "Architecture ADR-005 → Accepted", "source_id": "ccli-architecture-framework", "priority": "P0", "impact": "Wrong network segmentation; GOOSE failure", "action": "DRB decide switch vs dual PHY; update ADR-005", "blocks_gate": "Arch Freeze"},
    {"doc_id": "MD-006", "document": "Ethernet switch / PHY datasheet", "subsystem": "C1 Ethernet", "target": "reference/<MPN>-switch-phy.pdf", "source_id": "ccli-bom-switch-phy", "priority": "P1", "impact": "Cannot complete C1 schematic", "action": "Select MPN after ADR-005 + pin budget", "blocks_gate": "D12"},
    {"doc_id": "MD-007", "document": "RJ45 magjack datasheet ×4", "subsystem": "C1 Ethernet", "target": "reference/<MPN>-magjack.pdf", "source_id": "ccli-bom-magjack", "priority": "P1", "impact": "EMC/layout risk", "action": "Select with PHY/switch", "blocks_gate": "D12"},
    {"doc_id": "MD-008", "document": "Opto-isolated RS485 transceiver DS ×2", "subsystem": "C2 RS485", "target": "reference/<MPN>-rs485.pdf", "source_id": "ccli-bom-rs485", "priority": "P1", "impact": "C2 schematic hold", "action": "Select industrial isolated MPN", "blocks_gate": "D13"},
    {"doc_id": "MD-009", "document": "DI opto conditioner DS (10–120 V)", "subsystem": "C4 Digital I/O", "target": "reference/<MPN>-di.pdf", "source_id": "ccli-bom-di", "priority": "P1", "impact": "False PF2 / channel damage", "action": "Select after Wave B 24V learnings", "blocks_gate": "D11"},
    {"doc_id": "MD-010", "document": "DO relay datasheet (dry contact)", "subsystem": "C4 Digital I/O", "target": "reference/<MPN>-relay.pdf", "source_id": "ccli-bom-do", "priority": "P1", "impact": "Curtailment contact unreliable", "action": "Spec VA + inductive load class", "blocks_gate": "D11"},
    {"doc_id": "MD-011", "document": "GNSS module + antenna DS", "subsystem": "C5 GNSS", "target": "reference/<MPN>-gnss.pdf", "source_id": "ccli-bom-gnss", "priority": "P1", "impact": "No PPS/timestamp path", "action": "Select u-blox-class with PPS", "blocks_gate": "D9"},
    {"doc_id": "MD-012", "document": "12–24 V isolated PSU / DC-DC DS", "subsystem": "C10 Power", "target": "reference/<MPN>-psu.pdf", "source_id": "ccli-bom-psu", "priority": "P1", "impact": "Brownout / field failure", "action": "Size for SoM+PHY+relays+inrush", "blocks_gate": "D14"},
    {"doc_id": "MD-013", "document": "Secure element / TPM datasheet", "subsystem": "C6 Security", "target": "reference/<MPN>-se.pdf or SoM SKU letter", "source_id": "ccli-bom-se", "priority": "P1", "impact": "Keys in filesystem; 62443 fail", "action": "Pick ATECC/STSAFE/SE050 or prove on-SoM TPM", "blocks_gate": "D15"},
    {"doc_id": "MD-014", "document": "Product key hierarchy / HAB ceremony SOP", "subsystem": "C6 Security", "target": "08-engineering/CCI_Secure_Boot_Key_Hierarchy.md", "source_id": "ccli-secure-boot-keys", "priority": "P0", "impact": "Secure Boot theater without process", "action": "Author before Hardware Freeze", "blocks_gate": "HW Freeze"},
    {"doc_id": "MD-015", "document": "IEC 62443 zones & conduits + SL target", "subsystem": "Security", "target": "08-engineering/CCI_62443_Zones.md", "source_id": "ccli-62443-zones-extract", "priority": "P0", "impact": "Security compliance gap", "action": "Architecture workshop; map Eth_A/B/plant/USB/LTE", "blocks_gate": "D-CERT"},
    {"doc_id": "MD-016", "document": "MZ Automation libiec61850 commercial quote", "subsystem": "C3 Protocols", "target": "procurement quote", "source_id": "ccli-project-roadmap", "priority": "P1", "impact": "Legal risk shipping GPLv3", "action": "Request quote before product", "blocks_gate": "D-LIC"},
    {"doc_id": "MD-017", "document": "Energy analyzer Modbus register map", "subsystem": "C2/C3", "target": "07-protocols/…", "source_id": "ccli-modbus-analyzer-map", "priority": "P1", "impact": "L3 plant serial software blocked", "action": "Pick analyzer model; extract map", "blocks_gate": "D8"},
    {"doc_id": "MD-018", "document": "GOOSE lab test procedure", "subsystem": "C3 / Validation", "target": "08-engineering/CCI_GOOSE_Test_Procedure.md", "source_id": "ccli-goose-test", "priority": "P0", "impact": "Incorrect curtailment/event behavior", "action": "Author from validation strategy + Wave A", "blocks_gate": "Arch Freeze"},
    {"doc_id": "MD-019", "document": "IEC 60870-5-104 simulator choice + vectors", "subsystem": "C3 Protocols", "target": "08-engineering/CCI_IEC104_Lab.md", "source_id": "ccli-iec104-lab", "priority": "P1", "impact": "Operator Eth_B integration delay", "action": "Pick lib60870 or licensed client; write vectors", "blocks_gate": "FW Dev"},
    {"doc_id": "MD-020", "document": "Power load + thermal budget", "subsystem": "C10 / C9", "target": "08-engineering/CCI_Power_Thermal_Budget.md", "source_id": "ccli-power-thermal", "priority": "P2", "impact": "Cabinet overheating; PSU undersize", "action": "Expand Power_Tree with currents", "blocks_gate": "PCB"},
    {"doc_id": "MD-021", "document": "DIN-rail enclosure drawing", "subsystem": "C9 Mechanical", "target": "mechanical drawing", "source_id": "ccli-enclosure", "priority": "P2", "impact": "Form-factor / connector clash", "action": "Select enclosure after thermal envelope", "blocks_gate": "D18"},
    {"doc_id": "MD-022", "document": "SK0146 schematic RAG ingest", "subsystem": "Reuse / Bench", "target": "Telematry rag-structured/sk0146/", "source_id": "sk0146-schematic-index", "priority": "P0", "impact": "Knowledge leak during FCT/debug; lost reuse", "action": "Run ingest-sk0146-schematics.ps1", "blocks_gate": "D-SK0146"},
    {"doc_id": "MD-023", "document": "EMC connector family (RJ45 8/8) part PNs", "subsystem": "C1/C2 EMC", "target": "reference + D19 freeze", "source_id": "ccli-emc-connectors", "priority": "P2", "impact": "Certification failures", "action": "Freeze pinout + magnetics family", "blocks_gate": "D19"},
    {"doc_id": "MD-024", "document": "Altium ActiveBOM export", "subsystem": "Carrier", "target": "after schematic", "source_id": "—", "priority": "P2", "impact": "Fab BOM incomplete", "action": "Export after D3/D4 + MPN lock", "blocks_gate": "D7"},
    {"doc_id": "MD-025", "document": "Design Review Board ingest to RAG", "subsystem": "SYS", "target": "knowledge-base/08-engineering/CCI_Design_Review_Board_PF2.md", "source_id": "ccli-design-review-board-pf2", "priority": "P2", "impact": "DRB not queryable in BizChat/RAG", "action": "ingest-ccli.ps1 for DRB MD", "blocks_gate": "—"},
]

# Re-export KR and learning for standalone workbook sheets (from knowledge_risks_corpus)
from knowledge_risks_corpus import HEAT_MAP, KNOWLEDGE_RISKS, LEARNING_PLAN, REUSE_MATRIX  # noqa: E402
