/*=============================================================================
 * File       :  ENERGY.H
 *
 * Project    :  SK0153 - LINKY DIN 4G
 * Description:  PROGRAM - energy meter
 *
 * Copyright Shitek Technology SRL (c) 2010
 *=============================================================================*/




#ifndef __ENERGY_H__


#define __ENERGY_H__




/*=============================================================================
 * INCLUDES
 *=============================================================================*/
#include "typedef.h"




/*=============================================================================
 * DATA TYPE
 *=============================================================================*/

/*-----------------------------------------------------------------------------
 * Status
 *-----------------------------------------------------------------------------*/
/* ADC value status */
typedef struct
{
    s16  power_generated;                          /* power generated by the plant      */
    s16  power_drawn;                              /* power drawn     by the user       */
    s16  power_fed;                                /* power fed into the grid           */
    u8   status_adc_value;                         /* ADC value status                  */
    bool status_change_timer;                      /* indication of status change timer */
} ENERGY__STATUS__ADC_VALUE;


/*-----------------------------------------------------------------------------
 * Configurations
 *-----------------------------------------------------------------------------*/
/* configuration - "ADC value" */
typedef struct
{
    bool alarm_enabled_status;                     /* status           [OFF/ON]        */
    s16  adc_value;                                /* maximum ADC value for alarm (kW) */
} ENERGY__CONFIG__ADC_VALUE;




/*=============================================================================
 * FUNCTION PROTOTYPES
 *=============================================================================*/
/* task */
void Energy_TaskEnergy(void *argument);

/*-----------------------------------------------------------------------------
 * get/set
 *-----------------------------------------------------------------------------*/
/* get/set "ADC value" status */
void Energy_Status_AdcValue_GetDefault(ENERGY__STATUS__ADC_VALUE *ptr_data);
void Energy_Status_AdcValue_Get       (ENERGY__STATUS__ADC_VALUE *ptr_data);
void Energy_Status_AdcValue_Set       (ENERGY__STATUS__ADC_VALUE *ptr_data);
bool Energy_Status_AdcValue_IsValid   (ENERGY__STATUS__ADC_VALUE *ptr_data);

/* get/set "ADC value" configuration */
void Energy_Config_AdcValue_GetDefault(ENERGY__CONFIG__ADC_VALUE *ptr_data);
void Energy_Config_AdcValue_Get       (ENERGY__CONFIG__ADC_VALUE *ptr_data);
void Energy_Config_AdcValue_Set       (ENERGY__CONFIG__ADC_VALUE *ptr_data);
bool Energy_Config_AdcValue_IsValid   (ENERGY__CONFIG__ADC_VALUE *ptr_data);




#endif
